import type { Metadata } from "next";
import { Inter } from "next/font/google"; // ✅ Using a valid Google Font
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { QueryProvider } from "@/providers/query-provider"; // ✅ Ensure this has a named export
import { SheetProvider } from "@/providers/sheet-provider";
import {Toaster} from "@/components/ui/sonner";
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "PennyPilot",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.variable} antialiased`}>
          <QueryProvider>
            <SheetProvider/>
            <Toaster/>
            {children}</QueryProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
